DATA:
  TRAIN:
    ROOT_DIR: "data/dtu"
  VAL:
    ROOT_DIR: "data/dtu"
  TEST:
    ROOT_DIR: "data/dtu"
    NUM_VIEW: 7 # 5-dtu # 7-tt
    # dtu
    IMG_HEIGHT: 1152 # 960
    IMG_WIDTH: 1600 # 1280
    # TT
    # IMG_HEIGHT: 1080 # 1072/1080
    # IMG_WIDTH: 1920
    # eth3d
    # IMG_HEIGHT: 1280
    # IMG_WIDTH: 1920

    NUM_VIRTUAL_PLANE: 96 # 128
    INTER_SCALE: 2.13 # 1.6
  NUM_WORKERS: 16
MODEL:
  EDGE_CHANNELS: (32, 32, 64)
SCHEDULER:
  TYPE: "StepLR"
  INIT_EPOCH: 4
  MAX_EPOCH: 21
  StepLR:
    gamma: 0.9
    step_size: 2
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.001
  TYPE: 'RMSprop'
TRAIN:
  BATCH_SIZE: 4
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 50
TEST:
  WEIGHT: "outputs/dtu_wde3/model_014.pth"


